name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'assets/**'
      - '**/*.gitignore'
      - '**/*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'assets/**'
      - '**/*.gitignore'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: false
          go-version-file: go.mod

      - name: Verify gofmt
        run: |
          go fmt ./... && git add cmd internal models pkg &&
          git diff --cached --exit-code || (echo 'Please run "make fmt" to verify gofmt' && exit 1);
      - name: Verify govet
        run: |
          go vet ./... && git add cmd internal models pkg &&
          git diff --cached --exit-code || (echo 'Please run "make vet" to verify govet' && exit 1);

      - name: Build
        run: CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -o aoa .